---
- name: Create database volume
  community.docker.docker_volume:
    name: db-data
    state: present

- name: Launch database container
  community.docker.docker_container:
    name: database
    image: elodiefong/tp-devops-database:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: "pwd"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - name: app-network