---
- name: Launch application container
  community.docker.docker_container:
    name: backend
    image: elodiefong/tp-devops-simple-api:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/db"
      SPRING_DATASOURCE_USERNAME: "usr"
      SPRING_DATASOURCE_PASSWORD: "pwd"
    networks:
      - name: app-network
      - name: sec-network